apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "replik8or.fullname" . }}
  labels:
    {{- include "replik8or.labels" . | nindent 4 }}
roleRef:
  apiGroup: ClusterRoles
  kind: {{ include "replik8or.fullname" . }}
  name: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "replik8or.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
