apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "replik8or.fullname" . }}
  labels:
    {{- include "replik8or.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["create", "update", "get", "watch", "list", "delete"]
