apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "replik8or.serviceAccountName" . }}
  labels:
    {{- include "replik8or.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
